---

- name: Install and configure Nginx with PHP 8.2-FPM
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is enabled and started
      service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy custom Nginx default configuration
      template:
        src: templates/nginx_default.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'

    - name: Test Nginx configuration
      command: nginx -t

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
